#' Total Operation Time
#'
#' @param solution A list generated by one of the solution functions
#'
#' @return A numeric value
#' @export
#'
TOT <- function(solution) {
  tau <- 1
  solution$instance %>%
    dplyr::rowwise() %>%
    dplyr::mutate(Distance = euclid_norm(c(x-x.centroid, y-y.centroid))) %>%
    dplyr::group_by(`Centroid id`) %>%
    dplyr::summarise(OT = sum(`Arrival rate`*(Distance + tau))) %>%
    dplyr::summarise(TOT = sum(OT)) %>%
    as.numeric()
}

#' Within-Cluster sum of squares
#'
#' @param solution A list generated by one of the solution functions
#'
#' @return A numeric value
#' @export
#'
WCSS <- function(solution) {
  solution$instance %>%
    dplyr::rowwise() %>%
    dplyr::mutate(Distance = euclid_norm(c(x-x.centroid, y-y.centroid))) %>%
    dplyr::ungroup() %>%
    dplyr::summarise(WCSS = sum(Distance)) %>%
    as.numeric()
}
